export const USER_TYPES = {
    USER: "user",
    TRAINER: "trainer",
    ADMIN: "admin"
}

export const ITEM_STICKERS = {
    DEFAULT: 'DEFAULT',
    NEW: 'NEW',
    TRENDING: 'TRENDING',
    RECOMMENDED: 'RECOMMENDED',
    SALE: 'SALE'
}

export const ITEM_CATEGORIES = {
    ALL: 'ALL',
    MEMORY: 'MEMORY',
    CASE: 'CASE',
    PSU: 'PSU',
    HDD: 'HDD',
    SSD: 'SSD',
    MOTHERBOARD: 'MOTHERBOARD',
    PROCESSOR: 'PROCESSOR',
    COOLING_SYSTEM: 'COOLING_SYSTEM',
    VIDEO_CARD: 'VIDEO_CARD',
    MOUSE: 'MOUSE',
    KEYBOARD: 'KEYBOARD',
    HEADPHONE: 'HEADPHONE',
    SPEAKER: 'SPEAKER',
}